### ISSUE TITLE
Breakpoint background issue

### ISSUE THREAD

**Issue by rafandoo** [toby-j/jetbrains-github-dark-theme#15]
## Description

When setting a breakpoint on certain parts of a complex line (e.g., chained method calls), the red background doesn't cover the whole line.

![Image](https://github.com/user-attachments/assets/bbb331c6-2288-4643-bfc3-672f98ee2850)

## Steps to Reproduce:

1. Open a Java class with complex if or chained method calls.
2. Set a breakpoint mid-line in such an expression.
3. Observe that the red breakpoint background disappears partially.

## Environment

IntelliJ IDEA 2025.1.2 (Ultimate Edition)
Build #IU-251.26094.121, built on June 3, 2025
Source revision: 616fa4675f624
Runtime version: 21.0.7+9-b895.130 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-60-generic
Ubuntu 22.04.5 LTS; glibc: 2.35

**Comment by toby-j** [comment]
Noted. I've been meaning to come up with a new colour schema for the breakpoint line as I've seen it being problematic elsewhere.

**Comment by toby-j** [comment]
should be fixed in v.1.2.1

**Comment by rafandoo** [comment]
I cloned the repository and built version 1.2.1, but the issue still persists. 

![Image](https://github.com/user-attachments/assets/5dc41426-cda0-4319-ad41-0f012b1a75f4)

**Comment by toby-j** [comment]
Would you mind sending me a snippet I can run in a single file?

**Comment by rafandoo** [comment]
One more thing I noticed: if I open the same .java file outside the project’s source roots (e.g., just dragging it into the IDE or opening it as a standalone file), the red breakpoint background covers the entire line as expected. The partial-background bug only appears when the file is inside the actual Java project/module.

**Comment by toby-j** [comment]
Tried both of those with 1.2.1 and i'm getting a solid red line across both of them. If you run the debugger the background of the line should be yellow. Are you running any plugins that could affect it? I can't seem to re-create it.
