### ISSUE TITLE
`GitHub Dark Theme` theme within text boxes has light background

### ISSUE THREAD

**Issue by insyri** [toby-j/jetbrains-github-dark-theme#5]
So far, I was able to find that I only had this issue with GoLand and the `GitHub Dark Theme` theme. So far, I've tried:
- Selecting another theme and reselecting the theme
- Reinstalling the plugin
- Restarting the IDE

Attached is the log where I:
1. Switch the theme to an alternative theme -> switch the theme to `GitHub Dark Theme`
2. Disable -> enable the plugin
3. Uninstall -> restart the IDE -> install the plugin
4. Restart the IDE

[goland.log](https://github.com/toby-j/jetbrains-github-dark-theme/files/13823130/goland.log)

One line that kept showing up was this one:
```
WARN - #c.i.i.u.UIThemeBean - Do not set theme id in JSON (value=4b6007f7-b596-4ee2-96f9-968d3d3eb392)
```
Where the same UUID can be found within this [repository](https://github.com/toby-j/jetbrains-github-dark-theme/blob/b2360fea865468e73c57f090584ad2db61079b91/resources/themes/dark_dimmed/github_dark_dimmed.theme.json#L374).

I don't have this issue within other IDEs- Pycharm works fine. Although, RustRover seems to have no effectiveness when this plugin is installed; this would call for a separate issue.

![image](https://github.com/toby-j/jetbrains-github-dark-theme/assets/60794909/309add74-87db-48b3-8a6a-4fa445e33af6)

**Comment by insyri** [comment]
This problem extends onto the new UI as well.
[image](https://github.com/toby-j/jetbrains-github-dark-theme/assets/60794909/76b774ec-4300-4e29-9a87-804bddd7b8bc)

**Comment by jhonchu5** [comment]
I also have this problem.
![image](https://github.com/toby-j/jetbrains-github-dark-theme/assets/131732278/14d4bd33-ed39-4bf0-aac6-32a6ec0c29bb)

**Comment by Chaxiraxi** [comment]
Same problem here after plugin upate...

**Comment by insyri** [comment]
That's interesting, I have the same Intellij IDEA version and it works just fine.
![image](https://github.com/toby-j/jetbrains-github-dark-theme/assets/60794909/837acec1-c04d-4b88-9bb1-4fa3036578ad)

**Comment by insyri** [comment]
```
WARN - #c.i.i.u.UIThemeBean - Do not set theme id in JSON (value=4b6007f7-b596-4ee2-96f9-968d3d3eb392)
```
This same line shows up in the the Intelij IDEA logs too and it works, so I don't believe that this line is directly tied to this issue. And interestingly enough, this is new:
```
WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - GitHub_Dark_Theme color scheme is missing
```

**Comment by insyri** [comment]
> ```
> WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - GitHub_Dark_Theme color scheme is missing
> ```
This is also present in my PyCharm IDE logs, where this light background issue is not present.

**Comment by insyri** [comment]
I attempted to reinstall GoLand- the affected IDE in my case, and the behavior did not change.

**Comment by pog7776** [comment]
I just found that the Editor Color Scheme was being set to light by default.
I fixed it by pressing ctrl + `  and changing Editor Color Scheme to GitHub Dark / GitHub Dark Dimmed.

**Comment by insyri** [comment]
Sounds like what the warning was telling us, and is a valid temporary solution to this issue. I'll keep this issue open in case any fixes need to be made in the plugin so this behavior doesn't happen.

**Comment by toby-j** [comment]
This was still occuring on v1.1.1 if you reinstalled. The plugin.xml hasn't changed and I can't find an option from [the docs](https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html)

I suspect it's caused by the new UI coming out of beta and with the project being build with DevKit (Which intellij no longer includes pre-installed as a plugin so they might be phasing it out...)

As @pog7776 said you just need to assign your editor theme in the settings under Editor -> Color Scheme

**Comment by insyri** [comment]
Then should we add a comment on the README about this occurrence? It seems like multiple people might be having this issue, so it would be helpful to acknowledge it just in case. I've only had this issue with _this_ plugin, so I'm not sure if this is a general IDE issue or plugin specific.

Deciding how we should close this issue with the best course of action.

**Comment by toby-j** [comment]
I added a line to the README but I need to add it to the marketplace description so it'll show on the plugin marketplace dialog.

**Comment by ZeyoYT** [comment]
Hi, same issue here, nothing seems to fix it, for me this occurred in a very odd situation, there was a update to 3 plugins for me in intellij, i updated them, and restarted the IDE, and now my code part has white theme while other is normal, is there any fix for this, any workarounds?

**Comment by toby-j** [comment]
Closing as this seems to be out of my hands. IntelliJ auto selecting the editor theme doesn't seem to be working.

The solution is to just select it manually and IntelliJ will forever remember it.

_Appearance & Behaviour -> Appearance -> Theme_ and select what code editor theme you'd like.
